//set up all includes
const express = require('express');
const app = express();
const mysql = require('mysql');
const pug = require('pug');
const path = require('path');
const formidable = require('formidable');
const request = require('request');
const jwt = require("jsonwebtoken");
var cookieParser = require('cookie-parser');